apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-portfolio
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/portfolio-app.git
    path: k8s/    
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true